/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BottomNavBar: typeof import('./src/components/BottomNavBar.vue')['default']
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    CardItem: typeof import('./src/components/cards/CardItem.vue')['default']
    CardsCarousel: typeof import('./src/components/cards/CardsCarousel.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    MigakuHeroSection: typeof import('./src/components/MigakuHeroSection.vue')['default']
    ProgressNavBar: typeof import('./src/components/ProgressNavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLabel: typeof import('./src/components/base/StatusLabel.vue')['default']
    StudyPrimaryButton: typeof import('./src/components/base/StudyPrimaryButton.vue')['default']
  }
}
