/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    CardItem: typeof import('./src/components/cards/CardItem.vue')['default']
    CompletedCardsList: typeof import('./src/components/cards/CompletedCardsList.vue')['default']
    MigakuHeroSection: typeof import('./src/components/MigakuHeroSection.vue')['default']
    PrimaryButton: typeof import('./src/components/base/PrimaryButton.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    ProgressNavBar: typeof import('./src/components/ProgressNavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLabel: typeof import('./src/components/base/StatusLabel.vue')['default']
    TodayCardsList: typeof import('./src/components/cards/TodayCardsList.vue')['default']
  }
}
